"""Template for the generated base.py file."""

BASE_REPO_TEMPLATE = '''"""Auto-generated by RepoDB. Do not edit manually."""

from __future__ import annotations

import enum
from datetime import date, datetime
from decimal import Decimal
from typing import Any, Generic, Sequence, TypeVar, overload
from uuid import UUID

from pydantic import BaseModel, ConfigDict
from sqlalchemy import Select, func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import (
    DeclarativeBase,
    InstrumentedAttribute,
    QueryableAttribute,
    joinedload,
    selectinload,
    subqueryload,
)


# --- Filter Base Classes ---

class StringFilter(BaseModel):
    """Filter operators for string columns."""
    eq: str | None = None
    neq: str | None = None
    like: str | None = None
    ilike: str | None = None
    in_: list[str] | None = None
    not_in: list[str] | None = None


class IntFilter(BaseModel):
    """Filter operators for integer columns."""
    eq: int | None = None
    neq: int | None = None
    gt: int | None = None
    gte: int | None = None
    lt: int | None = None
    lte: int | None = None
    in_: list[int] | None = None
    not_in: list[int] | None = None


class FloatFilter(BaseModel):
    """Filter operators for float columns."""
    eq: float | None = None
    neq: float | None = None
    gt: float | None = None
    gte: float | None = None
    lt: float | None = None
    lte: float | None = None
    in_: list[float] | None = None
    not_in: list[float] | None = None


class NumericFilter(BaseModel):
    """Filter operators for Decimal/numeric columns."""
    eq: Decimal | None = None
    neq: Decimal | None = None
    gt: Decimal | None = None
    gte: Decimal | None = None
    lt: Decimal | None = None
    lte: Decimal | None = None
    in_: list[Decimal] | None = None
    not_in: list[Decimal] | None = None


class BoolFilter(BaseModel):
    """Filter operators for boolean columns."""
    eq: bool | None = None


class DateTimeFilter(BaseModel):
    """Filter operators for datetime columns."""
    eq: datetime | None = None
    neq: datetime | None = None
    gt: datetime | None = None
    gte: datetime | None = None
    lt: datetime | None = None
    lte: datetime | None = None


class DateFilter(BaseModel):
    """Filter operators for date columns."""
    eq: date | None = None
    neq: date | None = None
    gt: date | None = None
    gte: date | None = None
    lt: date | None = None
    lte: date | None = None


class UUIDFilter(BaseModel):
    """Filter operators for UUID columns."""
    eq: UUID | None = None
    neq: UUID | None = None
    in_: list[UUID] | None = None
    not_in: list[UUID] | None = None


# --- Load Strategy ---

class LoadStrategy(str, enum.Enum):
    """Eager loading strategies for relationships."""
    SELECT_IN = "selectin"
    JOINED = "joined"
    SUBQUERY = "subquery"


# --- Type Variables ---

ModelType = TypeVar("ModelType", bound=DeclarativeBase)
CreateDTOType = TypeVar("CreateDTOType", bound=BaseModel)
UpdateDTOType = TypeVar("UpdateDTOType", bound=BaseModel)
FilterType = TypeVar("FilterType", bound=BaseModel)
LoadOptionsType = TypeVar("LoadOptionsType", bound=BaseModel)


# --- Base Repository ---

class BaseRepository(
    Generic[ModelType, CreateDTOType, UpdateDTOType, FilterType, LoadOptionsType]
):
    """Generic async repository with filtering, loading options, and soft delete support."""

    model: type[ModelType]
    soft_deletable: bool = False

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    def _get_pk_columns(self) -> list[InstrumentedAttribute[Any]]:
        """Get the primary key column attributes for this model."""
        from sqlalchemy import inspect as sa_inspect
        mapper = sa_inspect(self.model)
        return [getattr(self.model, col.name) for col in mapper.primary_key]

    def _build_pk_clause(self, pk: Any) -> list[Any]:
        """Build WHERE clauses for primary key lookup."""
        pk_cols = self._get_pk_columns()
        if len(pk_cols) == 1:
            return [pk_cols[0] == pk]
        else:
            # Composite PK: pk is a Pydantic model with PK fields
            clauses = []
            pk_data = pk.model_dump()
            from sqlalchemy import inspect as sa_inspect
            mapper = sa_inspect(self.model)
            for col in mapper.primary_key:
                clauses.append(getattr(self.model, col.name) == pk_data[col.name])
            return clauses

    def _apply_soft_delete_filter(
        self, stmt: Select[tuple[ModelType]], include_deleted: bool = False
    ) -> Select[tuple[ModelType]]:
        """Apply soft delete filter if applicable."""
        if self.soft_deletable and not include_deleted:
            deleted_at = getattr(self.model, "deleted_at", None)
            if deleted_at is not None:
                stmt = stmt.where(deleted_at.is_(None))
        return stmt

    def _apply_filters(
        self, stmt: Select[tuple[ModelType]], filters: FilterType | None
    ) -> Select[tuple[ModelType]]:
        """Apply filter conditions to a query."""
        if filters is None:
            return stmt

        for field_name in filters.model_fields_set:
            field_filter = getattr(filters, field_name)
            if field_filter is None:
                continue

            column = getattr(self.model, field_name, None)
            if column is None:
                continue

            if isinstance(field_filter, BaseModel):
                # It\\'s a filter object (StringFilter, IntFilter, etc.)
                for op_name in field_filter.model_fields_set:
                    op_value = getattr(field_filter, op_name)
                    if op_value is None:
                        continue
                    stmt = self._apply_operator(stmt, column, op_name, op_value)
            else:
                # Direct value comparison
                stmt = stmt.where(column == field_filter)

        return stmt

    def _apply_operator(
        self,
        stmt: Select[tuple[ModelType]],
        column: InstrumentedAttribute[Any],
        op_name: str,
        value: Any,
    ) -> Select[tuple[ModelType]]:
        """Apply a single filter operator."""
        if op_name == "eq":
            stmt = stmt.where(column == value)
        elif op_name == "neq":
            stmt = stmt.where(column != value)
        elif op_name == "gt":
            stmt = stmt.where(column > value)
        elif op_name == "gte":
            stmt = stmt.where(column >= value)
        elif op_name == "lt":
            stmt = stmt.where(column < value)
        elif op_name == "lte":
            stmt = stmt.where(column <= value)
        elif op_name == "like":
            stmt = stmt.where(column.like(value))
        elif op_name == "ilike":
            stmt = stmt.where(column.ilike(value))
        elif op_name == "in_":
            stmt = stmt.where(column.in_(value))
        elif op_name == "not_in":
            stmt = stmt.where(column.not_in(value))
        return stmt

    def _apply_load_options(
        self,
        stmt: Select[tuple[ModelType]],
        load_options: LoadOptionsType | None,
    ) -> Select[tuple[ModelType]]:
        """Apply eager loading options to a query."""
        if load_options is None:
            return stmt

        from sqlalchemy import inspect as sa_inspect
        mapper = sa_inspect(self.model)

        for field_name in type(load_options).model_fields:
            value = getattr(load_options, field_name)
            if value is None or field_name == "load_strategy":
                continue

            # Find the relationship
            if field_name not in mapper.relationships:
                continue

            rel = mapper.relationships[field_name]
            related_model = rel.mapper.class_

            # Determine the strategy
            if isinstance(value, bool) and value is True:
                # Use smart default
                if rel.uselist:
                    strategy = LoadStrategy.SELECT_IN
                else:
                    strategy = LoadStrategy.JOINED
                loader = self._get_loader(strategy, getattr(self.model, field_name))
                stmt = stmt.options(loader)
            elif isinstance(value, LoadStrategy):
                loader = self._get_loader(value, getattr(self.model, field_name))
                stmt = stmt.options(loader)
            elif isinstance(value, BaseModel):
                # Nested load options
                nested_strategy_field = getattr(value, "load_strategy", None)
                if nested_strategy_field is not None:
                    strategy = nested_strategy_field
                elif rel.uselist:
                    strategy = LoadStrategy.SELECT_IN
                else:
                    strategy = LoadStrategy.JOINED

                loader = self._get_loader(strategy, getattr(self.model, field_name))

                # Apply nested options
                for nested_field in value.model_fields:
                    nested_value = getattr(value, nested_field)
                    if nested_value is None or nested_field == "load_strategy":
                        continue
                    if nested_field in sa_inspect(related_model).relationships:
                        nested_rel = sa_inspect(related_model).relationships[nested_field]
                        if isinstance(nested_value, bool) and nested_value is True:
                            if nested_rel.uselist:
                                nested_strat = LoadStrategy.SELECT_IN
                            else:
                                nested_strat = LoadStrategy.JOINED
                            nested_loader = self._get_loader(
                                nested_strat,
                                getattr(related_model, nested_field),
                            )
                            loader = loader.options(nested_loader)
                        elif isinstance(nested_value, LoadStrategy):
                            nested_loader = self._get_loader(
                                nested_value,
                                getattr(related_model, nested_field),
                            )
                            loader = loader.options(nested_loader)

                stmt = stmt.options(loader)

        return stmt

    @staticmethod
    def _get_loader(
        strategy: LoadStrategy, attr: QueryableAttribute[Any]
    ) -> Any:
        """Get the appropriate loader function for a strategy."""
        if strategy == LoadStrategy.JOINED:
            return joinedload(attr)
        elif strategy == LoadStrategy.SUBQUERY:
            return subqueryload(attr)
        else:
            return selectinload(attr)

    def _apply_ordering(
        self,
        stmt: Select[tuple[ModelType]],
        order_by: str | list[tuple[str, str]] | None,
    ) -> Select[tuple[ModelType]]:
        """Apply ordering to a query."""
        if order_by is None:
            return stmt

        if isinstance(order_by, str):
            column = getattr(self.model, order_by, None)
            if column is not None:
                stmt = stmt.order_by(column)
        elif isinstance(order_by, list):
            for col_name, direction in order_by:
                column = getattr(self.model, col_name, None)
                if column is not None:
                    if direction.lower() == "desc":
                        stmt = stmt.order_by(column.desc())
                    else:
                        stmt = stmt.order_by(column.asc())
        return stmt

    async def get_by_id(
        self,
        pk: Any,
        load_options: LoadOptionsType | None = None,
        include_deleted: bool = False,
    ) -> ModelType | None:
        """Fetch a single record by primary key."""
        stmt = select(self.model)
        for clause in self._build_pk_clause(pk):
            stmt = stmt.where(clause)
        stmt = self._apply_soft_delete_filter(stmt, include_deleted)
        stmt = self._apply_load_options(stmt, load_options)
        result = await self.session.execute(stmt)
        return result.scalars().first()

    async def get_many(
        self,
        filters: FilterType | None = None,
        load_options: LoadOptionsType | None = None,
        order_by: str | list[tuple[str, str]] | None = None,
        limit: int | None = None,
        offset: int | None = None,
        include_deleted: bool = False,
    ) -> list[ModelType]:
        """Fetch multiple records with filtering, ordering, and pagination."""
        stmt = select(self.model)
        stmt = self._apply_soft_delete_filter(stmt, include_deleted)
        stmt = self._apply_filters(stmt, filters)
        stmt = self._apply_load_options(stmt, load_options)
        stmt = self._apply_ordering(stmt, order_by)
        if limit is not None:
            stmt = stmt.limit(limit)
        if offset is not None:
            stmt = stmt.offset(offset)
        result = await self.session.execute(stmt)
        return list(result.scalars().all())

    async def create(self, dto: CreateDTOType) -> ModelType:
        """Create a single record."""
        data = dto.model_dump()
        instance = self.model(**data)
        self.session.add(instance)
        await self.session.flush()
        return instance

    async def create_many(self, dtos: list[CreateDTOType]) -> list[ModelType]:
        """Create multiple records."""
        instances = []
        for dto in dtos:
            data = dto.model_dump()
            instance = self.model(**data)
            self.session.add(instance)
            instances.append(instance)
        await self.session.flush()
        return instances

    async def update(self, dto: UpdateDTOType) -> ModelType | None:
        """Update a record. Uses exclude_unset to only update provided fields."""
        data = dto.model_dump(exclude_unset=True)

        # Extract PK fields
        from sqlalchemy import inspect as sa_inspect
        mapper = sa_inspect(self.model)
        pk_col_names = [col.name for col in mapper.primary_key]

        if len(pk_col_names) == 1:
            pk = data.pop(pk_col_names[0])
        else:
            # Composite PK - build a dict of PK values
            pk_dict = {col_name: data.pop(col_name) for col_name in pk_col_names}
            pk = type("PK", (), pk_dict)()  # simple object with attributes

        # Fetch the instance
        stmt = select(self.model)
        if len(pk_col_names) == 1:
            stmt = stmt.where(getattr(self.model, pk_col_names[0]) == pk)
        else:
            for col_name in pk_col_names:
                stmt = stmt.where(
                    getattr(self.model, col_name) == getattr(pk, col_name, pk_dict[col_name])
                )
        stmt = self._apply_soft_delete_filter(stmt)

        result = await self.session.execute(stmt)
        instance = result.scalars().first()
        if instance is None:
            return None

        for key, value in data.items():
            setattr(instance, key, value)
        await self.session.flush()
        return instance

    async def delete(self, pk: Any) -> bool:
        """Hard delete a record by primary key."""
        stmt = select(self.model)
        for clause in self._build_pk_clause(pk):
            stmt = stmt.where(clause)
        result = await self.session.execute(stmt)
        instance = result.scalars().first()
        if instance is None:
            return False
        await self.session.delete(instance)
        await self.session.flush()
        return True

    async def soft_delete(self, pk: Any) -> ModelType | None:
        """Soft delete a record by setting deleted_at."""
        if not self.soft_deletable:
            raise NotImplementedError("This model does not support soft delete")
        stmt = select(self.model)
        for clause in self._build_pk_clause(pk):
            stmt = stmt.where(clause)
        stmt = self._apply_soft_delete_filter(stmt)
        result = await self.session.execute(stmt)
        instance = result.scalars().first()
        if instance is None:
            return None
        setattr(instance, "deleted_at", datetime.utcnow())
        await self.session.flush()
        return instance

    async def restore(self, pk: Any) -> ModelType | None:
        """Restore a soft-deleted record."""
        if not self.soft_deletable:
            raise NotImplementedError("This model does not support soft delete")
        stmt = select(self.model)
        for clause in self._build_pk_clause(pk):
            stmt = stmt.where(clause)
        # Explicitly look for deleted records
        deleted_at = getattr(self.model, "deleted_at", None)
        if deleted_at is not None:
            stmt = stmt.where(deleted_at.is_not(None))
        result = await self.session.execute(stmt)
        instance = result.scalars().first()
        if instance is None:
            return None
        setattr(instance, "deleted_at", None)
        await self.session.flush()
        return instance

    async def count(
        self,
        filters: FilterType | None = None,
        include_deleted: bool = False,
    ) -> int:
        """Count records matching the given filters."""
        from sqlalchemy import inspect as sa_inspect
        mapper = sa_inspect(self.model)
        pk_col = getattr(self.model, mapper.primary_key[0].name)
        stmt = select(func.count(pk_col))
        # We need to apply filters manually since stmt type is different
        if self.soft_deletable and not include_deleted:
            deleted_at = getattr(self.model, "deleted_at", None)
            if deleted_at is not None:
                stmt = stmt.where(deleted_at.is_(None))
        if filters is not None:
            for field_name in filters.model_fields_set:
                field_filter = getattr(filters, field_name)
                if field_filter is None:
                    continue
                column = getattr(self.model, field_name, None)
                if column is None:
                    continue
                if isinstance(field_filter, BaseModel):
                    for op_name in field_filter.model_fields_set:
                        op_value = getattr(field_filter, op_name)
                        if op_value is None:
                            continue
                        if op_name == "eq":
                            stmt = stmt.where(column == op_value)
                        elif op_name == "neq":
                            stmt = stmt.where(column != op_value)
                        elif op_name == "gt":
                            stmt = stmt.where(column > op_value)
                        elif op_name == "gte":
                            stmt = stmt.where(column >= op_value)
                        elif op_name == "lt":
                            stmt = stmt.where(column < op_value)
                        elif op_name == "lte":
                            stmt = stmt.where(column <= op_value)
                        elif op_name == "like":
                            stmt = stmt.where(column.like(op_value))
                        elif op_name == "ilike":
                            stmt = stmt.where(column.ilike(op_value))
                        elif op_name == "in_":
                            stmt = stmt.where(column.in_(op_value))
                        elif op_name == "not_in":
                            stmt = stmt.where(column.not_in(op_value))
        result = await self.session.execute(stmt)
        count = result.scalar()
        return count if count is not None else 0
'''
