"""Main orchestrator for code generation."""

from __future__ import annotations

import os
from pathlib import Path

from ..introspection.ir import ModelIR
from .base_repo_template import BASE_REPO_TEMPLATE
from .dto import generate_dto
from .filters import generate_filters
from .load_options import generate_load_options
from .repository import generate_repository, generate_init
from .utils import model_name_to_snake


def generate_all(models: list[ModelIR], output_dir: str | Path) -> dict[str, int]:
    """Generate all repository code for the given models.

    Returns a summary dict with counts.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Filter out association tables
    gen_models = [m for m in models if not m.is_association_table]

    stats = {
        "models_found": len(models),
        "models_generated": 0,
        "skipped_association_tables": len(models) - len(gen_models),
    }

    # Write base.py
    _write_file(output_dir / "base.py", BASE_REPO_TEMPLATE)

    # Write top-level __init__.py
    init_imports = []
    for model in gen_models:
        snake = model_name_to_snake(model.class_name)
        init_imports.append(f"from .{snake} import {model.class_name}Repository")

    init_content = '"""Auto-generated by RepoDB. Do not edit manually."""\n\n'
    init_content += "\n".join(sorted(init_imports))
    init_content += "\n"
    _write_file(output_dir / "__init__.py", init_content)

    # Generate per-model packages
    for model in gen_models:
        try:
            _generate_model_package(model, gen_models, output_dir)
            stats["models_generated"] += 1
        except Exception as e:
            print(f"Warning: Failed to generate for {model.class_name}: {e}")

    return stats


def _generate_model_package(
    model: ModelIR, all_models: list[ModelIR], output_dir: Path
) -> None:
    """Generate a complete package for a single model."""
    snake = model_name_to_snake(model.class_name)
    pkg_dir = output_dir / snake
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # __init__.py
    _write_file(pkg_dir / "__init__.py", generate_init(model))

    # dto.py
    _write_file(pkg_dir / "dto.py", generate_dto(model))

    # filters.py
    _write_file(pkg_dir / "filters.py", generate_filters(model))

    # load_options.py
    _write_file(pkg_dir / "load_options.py", generate_load_options(model, all_models))

    # repository.py
    _write_file(pkg_dir / "repository.py", generate_repository(model))


def _write_file(path: Path, content: str) -> None:
    """Write content to a file, creating parent dirs if needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
