"""Shared utilities for all RepoGen generators."""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

import jinja2

from repogen.introspection.ir import ColumnIR

# Resolve the templates directory relative to this file's location:
# generators/ -> repogen/ -> templates/
_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"
_JINJA_ENV = jinja2.Environment(
    loader=jinja2.FileSystemLoader(str(_TEMPLATES_DIR)),
    keep_trailing_newline=True,
)


def _get_header(model_class_name: str, module_path: str) -> str:
    """Return the auto-generated file header comment."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return (
        f"# AUTO-GENERATED by RepoGen — do not edit manually.\n"
        f"# Model  : {model_class_name}\n"
        f"# Source : {module_path}\n"
        f"# Generated at: {ts}"
    )


def _snake_case(name: str) -> str:
    """Convert a CamelCase name to snake_case."""
    # Insert underscore before sequences of uppercase letters followed by lowercase
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    # Insert underscore before a single uppercase letter preceded by lowercase/digit
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.lower()


def _get_template(template_name: str) -> jinja2.Template:
    """Load a Jinja2 template by name from the templates directory."""
    return _JINJA_ENV.get_template(template_name)


def _python_type_to_str(t: type) -> str:
    """Convert a Python type object to its string representation for code generation."""
    if t is int:
        return "int"
    if t is float:
        return "float"
    if t is str:
        return "str"
    if t is bool:
        return "bool"
    if t is bytes:
        return "bytes"
    # Named types — match by qualified name to avoid import issues
    name = getattr(t, "__name__", None) or getattr(t, "_name", None) or str(t)
    if name in ("datetime",):
        return "datetime"
    if name in ("date",):
        return "date"
    if name in ("UUID",):
        return "UUID"
    if name in ("Decimal",):
        return "Decimal"
    # Fallback: use the bare class name
    return name


def _get_type_imports(columns: list[ColumnIR]) -> str:
    """
    Build the necessary import lines for special types (datetime, date, UUID, Decimal)
    used in the given columns.  Returns an empty string when no special imports are needed.
    """
    type_names: set[str] = set()
    for col in columns:
        name = _python_type_to_str(col.python_type)
        type_names.add(name)

    datetime_imports: list[str] = []
    if "datetime" in type_names:
        datetime_imports.append("datetime")
    if "date" in type_names:
        datetime_imports.append("date")

    lines: list[str] = []
    if datetime_imports:
        lines.append(f"from datetime import {', '.join(datetime_imports)}")
    if "UUID" in type_names:
        lines.append("from uuid import UUID")
    if "Decimal" in type_names:
        lines.append("from decimal import Decimal")

    return "\n".join(lines)
