"""Generator for the _internals shared-utility package."""
from __future__ import annotations

from pathlib import Path

from repogen.generators.base import _get_header, _get_template

# The three internal templates to render (relative to the templates dir)
_INTERNAL_TEMPLATES = [
    ("internals/filter_utils.py.j2", "filter_utils.py"),
    ("internals/loading_utils.py.j2", "loading_utils.py"),
    ("internals/soft_delete.py.j2", "soft_delete.py"),
]

# Sentinel used as model_class_name / module_path in the header
_INTERNALS_HEADER_MODEL = "_internals"
_INTERNALS_HEADER_MODULE = "repogen._internals"


def generate_internals(output_dir: Path) -> None:
    """
    Render the three internal utility templates and write them into
    ``<output_dir>/_internals/``.  Also creates a minimal ``__init__.py``
    for the package.

    Parameters
    ----------
    output_dir:
        The root directory where the generated code lives.  The
        ``_internals`` sub-directory is created here.
    """
    output_dir = Path(output_dir)
    internals_dir = output_dir / "_internals"
    internals_dir.mkdir(parents=True, exist_ok=True)

    header = _get_header(_INTERNALS_HEADER_MODEL, _INTERNALS_HEADER_MODULE)

    for template_name, output_file in _INTERNAL_TEMPLATES:
        template = _get_template(template_name)
        content = template.render(header=header)
        out_path = internals_dir / output_file
        out_path.write_text(content)

    # Create __init__.py for the package (empty is fine)
    init_path = internals_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(
            "# AUTO-GENERATED by RepoGen — do not edit manually.\n"
        )
